"""Initial migration

Revision ID: 2e4b7bcdf855
Revises: 05aed124a3f8
Create Date: 2024-01-27 17:06:52.888651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4b7bcdf855'
down_revision: Union[str, None] = '05aed124a3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mailing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_client', sa.String(), nullable=False),
    sa.Column('subject_mailing', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['email_client'], ['client.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailing')
    op.drop_table('client')
    # ### end Alembic commands ###
