"""Initial migration

Revision ID: 5b8982a332fc
Revises: fca32a5da14d
Create Date: 2024-01-27 13:23:29.070633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b8982a332fc"
down_revision: Union[str, None] = "fca32a5da14d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "completed_mailings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email_client", sa.String(), nullable=False),
        sa.Column("subject_mailing", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_client"], ["clients.email"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "queue_mailings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email_client", sa.String(), nullable=False),
        sa.Column("subject_mailing", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_client"], ["clients.email"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("queue_mailings")
    op.drop_table("completed_mailings")
    # ### end Alembic commands ###
