"""Initial migration

Revision ID: 7d491dde57ce
Revises: 5b8982a332fc
Create Date: 2024-01-27 14:47:44.845951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7d491dde57ce"
down_revision: Union[str, None] = "5b8982a332fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("queue_mailings")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queue_mailings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email_client", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("subject_mailing", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["email_client"],
            ["clients.email"],
            name="queue_mailings_email_client_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="queue_mailings_pkey"),
    )
    # ### end Alembic commands ###
