"""Initial migration

Revision ID: b7254697c868
Revises: cf6a772ac508
Create Date: 2024-01-27 12:28:23.608610

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7254697c868"
down_revision: Union[str, None] = "cf6a772ac508"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mailings", sa.Column("subject_mailing", sa.String(), nullable=False))
    op.drop_column("mailings", "text_mailing")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mailings",
        sa.Column("text_mailing", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("mailings", "subject_mailing")
    # ### end Alembic commands ###
