"""Initial migration

Revision ID: cf6a772ac508
Revises: 5e184cc51868
Create Date: 2024-01-25 22:52:30.600101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf6a772ac508"
down_revision: Union[str, None] = "5e184cc51868"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mailings", sa.Column("email_client", sa.String(), nullable=False))
    op.drop_constraint("mailings_client_fkey", "mailings", type_="foreignkey")
    op.create_foreign_key(
        None, "mailings", "clients", ["email_client"], ["email"], ondelete="CASCADE"
    )
    op.drop_column("mailings", "client")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mailings",
        sa.Column("client", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "mailings", type_="foreignkey")
    op.create_foreign_key(
        "mailings_client_fkey",
        "mailings",
        "clients",
        ["client"],
        ["email"],
        ondelete="CASCADE",
    )
    op.drop_column("mailings", "email_client")
    # ### end Alembic commands ###
